// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccessibleAutocompleteController from "./accessible_autocomplete_controller.js"
application.register("accessible-autocomplete", AccessibleAutocompleteController)

import ConditionalQuestionController from "./conditional_question_controller.js"
application.register("conditional-question", ConditionalQuestionController)

import NumericQuestionController from "./numeric_question_controller.js"
application.register("numeric-question", NumericQuestionController)

import SoftValidationsController from "./soft_validations_controller.js"
application.register("soft-validations", SoftValidationsController)

import TasklistController from "./tasklist_controller.js"
application.register("tasklist", TasklistController)

import GovukfrontendController from "./govukfrontend_controller.js"
application.register("govukfrontend", GovukfrontendController)
