module Exports::SalesLogExportConstants
  MAX_XML_RECORDS = 10_000
  LOG_ID_OFFSET = 300_000_000_000

  EXPORT_MODE = {
    xml: 1,
    csv: 2,
  }.freeze

  EXPORT_FIELDS = Set["id",
                      "status",
                      "day",
                      "month",
                      "year",
                      "duplicate_set_id",
                      "createddate",
                      "uploaddate",
                      "owningorgid",
                      "owningorgname",
                      "maningorgid",
                      "maningorgname",
                      "username",
                      "usernameid",
                      "purchid",
                      "type",
                      "ownership",
                      "collectionyear",
                      "jointmore",
                      "joint",
                      "beds",
                      "ethnic",
                      "ethnicgroup1",
                      "liveinbuyer1",
                      "builtype",
                      "proptype",
                      "noint",
                      "liveinbuyer2",
                      "privacynotice",
                      "wheel",
                      "hholdcount",
                      "la",
                      "income1",
                      "inc1nk",
                      "inc1mort",
                      "income2",
                      "inc2nk",
                      "savingsnk",
                      "savings",
                      "prevown",
                      "amendedby",
                      "amendedbyid",
                      "mortgage",
                      "inc2mort",
                      "hb",
                      "frombeds",
                      "staircase",
                      "stairbought",
                      "stairowned",
                      "mrent",
                      "resale",
                      "deposit",
                      "cashdis",
                      "disabled",
                      "value",
                      "equity",
                      "discount",
                      "grant",
                      "ppcodenk",
                      "ppostc1",
                      "ppostc2",
                      "prevloc",
                      "prevlocname",
                      "previouslaknown",
                      "hhregres",
                      "hhregresstill",
                      "proplen",
                      "hasmscharge",
                      "mscharge",
                      "prevten",
                      "mortgageused",
                      "wchair",
                      "armedforcesspouse",
                      "hoday",
                      "homonth",
                      "hoyear",
                      "fromprop",
                      "socprevten",
                      "mortlen1",
                      "extrabor",
                      "hhtype",
                      "postcode",
                      "islainferred",
                      "bulkuploadid",
                      "value_value_check",
                      "prevshared",
                      "staircasesale",
                      "ethnicgroup2",
                      "ethnic2",
                      "buy2living",
                      "prevten2",
                      "uprn",
                      "address1",
                      "address2",
                      "towncity",
                      "county",
                      "laname",
                      "creationmethod",
                      "nationalityall1",
                      "nationalityall2",
                      "mscharge_value_check",
                      "address1input",
                      "postcodeinput",
                      "address_search_value_check",
                      "uprnselected",
                      "bulkaddress1",
                      "bulkaddress2",
                      "bulktowncity",
                      "bulkcounty",
                      "bulkpostcode",
                      "bulkla",
                      "createdby",
                      "createdbyid",
                      "has_estate_fee",
                      "estate_fee",
                      "firststair",
                      "numstair",
                      "stairlastday",
                      "stairlastmonth",
                      "stairlastyear",
                      "stairinitialyear",
                      "stairinitialmonth",
                      "stairinitialday"]

  (1..6).each do |index|
    EXPORT_FIELDS << "age#{index}"
    EXPORT_FIELDS << "ecstat#{index}"
    EXPORT_FIELDS << "sex#{index}"
  end

  (2..6).each do |index|
    EXPORT_FIELDS << "relat#{index}"
  end
end
