name: Manual review app build and deploy

concurrency:
  group: deploy-review${{ inputs.pr_number }}

on:
  workflow_dispatch:
    inputs:
      pr_number:
        required: true
        type: string
        description: "The PR number of the review app to deploy code for. Note: this is NOT the ticket number"

defaults:
  run:
    shell: bash

jobs:
  code:
    name: Deploy review app code
    uses: ./.github/workflows/aws_deploy.yml
    with:
      aws_account_id: 837698168072
      aws_role_prefix: core-dev
      aws_task_prefix: core-review-${{ inputs.pr_number }}
      concurrency_tag: ${{ inputs.pr_number }}
      environment: review
    permissions:
      id-token: write
